language: android

jdk: oraclejdk8

sudo: false

dist: precise

licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-preview-license'
  - 'android-sdk-license-.+'
  - 'android-sdk-license'
  - 'google-gdk-license-.+'
  - '.+'

android:
  components:
  - tools
  - build-tools-25.0.2
  - android-25
  - platform-tools
  - extra-android-m2repository
  - extra-android-support
  - tools

before_install:
  - chmod +x gradlew

script:
  - "./gradlew assembleRelease"